### ISSUE TITLE
createAnswer returns RTCSessionDescription instead of RTCSessionDescriptionInit

### ISSUE THREAD

**Issue by eskimor** [ghcjs/jsaddle-dom#3]
In jsaddle-dom there are two createAnswer functions one is generated and does return a RTCSessionDescriptionInit, the other is custom and does a conversion to RTCSessionDescription. The custom one is exported. This is unfortunate for two reasons:

1. the return value of createAnswer is used in setLocalDescription which expects a RTCSessionDescriptionInit.
2. ghcjs-dom only has the generated one, which returns a RTCSessionDescriptionInit. Thus it seems to be incompatible with jsaddle-dom.

I can file a PR for exporting the generated function and maybe even dropping the custom one if this is the way to go. Am I missing something?

**Comment by hamishmack** [comment]
Thanks for fixing this.
